reviewing my work
misikira/my-review pull request #1
Opened 2023-02-27 13:59 UTC by misikira

2023-02-27 14:18 UTC, misikira reviewed
1. good use semantic html
2. design looks good
3.  <div class="header">
             <h1>COMPUTERS AND ALL ACCESORIES</h1>
             <textarea name="enter email" rows="1" cols="40"></textarea>
             <button type="button" class="btn btn-primary">Get Started</button>

          </div>
here try to use section HTML semantic instead of using div it makes your code readable by assistive technology

2023-02-27 14:26 UTC, misikira reviewed
in my opinion, the readme file is empty try to put some info about your project to the readers this makes them understand your project better. here you can find a good template and customize it according to your  project [https://github.com/microverseinc/readme-template/blob/master/README.md](URL)

2023-02-27 14:55 UTC, joskalenda commented
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @misikira , |
|Good job so far! You still need to work on some issues to go to the next project, but you are almost there! |
| <img src="https://media0.giphy.com/media/ckGndVa23sCk9pae4l/giphy.gif"/> |

## Required Changes ♻️

- [ ] Hey @misikira, thanks for making this great effort, I think you have made an awesome job, but I am sure we can do better.
- The first comment is point to a `div` tag that be replaced by a more semantic tag, the question am asking is, how should the student know this is the div you are talking about if he/she has more than one in the HTML file?... the solution to this question is using github inline comment feature, take you time to read a bit about it [here](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) and make sure you use it in the next request.
- We are not making orders when giving reviews, please make sure you give suggestions instead, `I think, in my opinion, etc...` this way the student will not feel forced to execute a certain change.
- the last one is, explaining the reason for your required changes, see you said, `the student should add some info in the readme`, okay, but why? you can explain this by sending an article's microverse link to the student on how to set up the repo in a professional way and blbalaallalaaa.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-27 15:11 UTC, misikira commented on index.html
> -    <link rel="stylesheet" href="./style.css">
can you remove this stylesheet link it's duplcated

2023-02-27 16:16 UTC, misikira commented
@joskalenda i have an issues in index.html i can't comment starting from line 10 all the way down can you help with this?

2023-02-27 16:28 UTC, misikira commented
i put the inline commets and included the link to the reademe file template

2023-02-27 16:58 UTC, brainconnect93 requested changes
# STATUS: Changes Required :recycle:

### Hi @misikira, 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 

### Changes Required

- [ ] As requested by the previous reviewer, Kindly use the following comment raised by him.

  - Make sure your comment is inform of suggestion instead of given an order.
    > N.B: 1. The student phrased the comments politely, as suggestions instead of orders. For example: This is a polite suggestion: *"I think it would be better to use semantic tags"
This reads as an order: *"Use semantic tags"
   - Also, I would suggest you give reason `WHY` you are requesting those changes.
     > N.B: The student always includes an explanation, a "why", for each requested change. For example: This is a well-explained request: *Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible
This request lacks a "why": *Why don't you use an article tag here instead of a div?

  - I noticed you raised an issue that you could not use inline comment on your HTML file on line 10. But from my end I can see somewhere in your CSS file where you can make an inline comment. You can comment where you commented out some codes. Use this [Link ](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md#how-to-communicate)to learn more on how to make an inline comment


1. 
- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 06:31 UTC, misikira reviewed
Hi @misikira
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in!

2023-02-28 11:35 UTC, IngDavidTM approved these changes
Hi @misikira  🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- It has two inline comments ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 11:36 UTC, misikira commented
thank you

On Tue, Feb 28, 2023 at 3:35 AM David A. Tamayo ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi <STUDENT_NAME> 🙋‍♂️,
> ✔️ Status: APPROVED 🏆 🎉 🎊
>
> You have done a great job on this project, keep it up 👍 🥇. Your project
> is complete! There is nothing else to say other than... it's time to merge
> it [image: :shipit:]
> Congratulations! 🎉💯🌟
> Top highlight 🎯
>
>    - It has two inline comments ✅
>
>
> <https://camo.githubusercontent.com/5d2ef7789f70f7829b4c278f18e77bc67da5412b06f77ddc5b0c1b0cff45702a/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/misikira/my-review/pull/1#pullrequestreview-1317332981>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJ7Y7HBFSGAHVHRPC6EQBBLWZXPJFANCNFSM6AAAAAAVJOAZPU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-28 11:45 UTC, merged